package edu.gatech.seclass.jobcompare6300.core;

public enum COMPARISON_SETTINGS_OPTIONS {
    REMOTE_WORK_POSSIBILITY_WEIGHT,
    YEARLY_SALARY_WEIGHT,
    YEARLY_BONUS_WEIGHT,
    RETIREMENT_BENEFITS_WEIGHT,
    LEAVE_TIME_WEIGHT
}
